### ISSUE TITLE
Can I maintain this?

### ISSUE THREAD

**Issue by bdharrington7** [NodeBB-Community/nodebb-plugin-spoilers#12]
@psychobunny I still use this pretty actively. Can I be a maintainer if you don't want to support it anymore?

**Comment by psychobunny** [comment]
Absolutely, thanks! 

I can move this to https://github.com/NodeBB-Community/ and give you npm access, or we can move this to your GH, let me know what works for you

**Comment by bdharrington7** [comment]
Let's just move it to the nodebb community group. Thanks!

**Comment by psychobunny** [comment]
Great :) Hope you're doing well btw! And I realize I totally ignored your PR in this repo -- sorry and hope you can take better care of it than I have!

https://github.com/NodeBB-Community/nodebb-plugin-spoilers
